backend:
  name: github
  repo: blubMe/blog

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: posts
    folder: src/pages/post
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image}